# Path to input directory
input_dir: "/path/to/input/reads/"

# Where are the final results published?
output_dir: "/path/to/output/directory"


# workflow parameters

# run preprocessing/qc workflow
run_preprocessing: true

# ignore orphan reads after qc
drop_orphans: false

# qc parameters
# (also refer to: https://jgi.doe.gov/data-and-tools/bbtools/bb-tools-user-guide/bbduk-guide/)

# minimum read length [bp]
qc_minlen: 45

# bbduk wgs
# qtrim=rl trimq=3 : gentle quality trimming (only discard bases < phred 3; phred 2 = junk marker) on either side (rl) of the read
# maq=25 : discard reads below average quality of pred 25
# ref=?? ktrim=r k=23 mink=11 hdist=1 tpe tbo : right-side k-mer based adapter clipping with 1 mismatch allowed, try overlap-detection (tbo), and trim pairs to same length (tpe) upon adapter detection -- NOTE: ref-parameter is set within workflow
# ftm=5 : get rid of (n*5)+1st base (last sequencing cycle illumina garbage) -- NOTE: unset for preprocessed data
# entropy=0.5 entropywindow=50 entropyk=5 : discard low complexity sequences
# LEGACY SETTING
# qc_params_shotgun: "qtrim=rl trimq=3 maq=21 ktrim=r k=23 mink=11 hdist=1 ftm=5 entropy=0.5 entropywindow=50 entropyk=5 tpe tbo"
# METAPHLAN/SAMESTR-SPECIFIC PARAMETER SETTING
# mlf=0.5 discard reads if trimmed to < 50% of raw length
qc_params_shotgun: "maq=3 qtrim=rl trimq=21 ktrim=r k=23 mlf=0.5 mink=11 hdist=1 entropy=0.5 entropywindow=50 entropyk=5 tpe tbo"


# decontamination parameters

# run host-decontamination subworkflow
# false or "hostile" (requires hostile_db)
remove_host: false

hostile_db: null

# profiling parameters

# metaphlan4 database
mp4_db: "/path/to/metaphlan4/database"

# samestr database
samestr_db: "/path/to/samestr/database"

